### ISSUE TITLE
Waiting for IRC

### ISSUE THREAD

**Issue by toadsucks** [EldinZenderink/LittleWeeb#12]
I have left this program open or about 20 minutes and it hasn't moved passed this screen.
What could be going wrong?
![image](https://user-images.githubusercontent.com/26445296/35768053-ddcab4ae-08bb-11e8-8151-ebcddc8ee1f5.png)

**Comment by EldinZenderink** [comment]
The irc client behind it generates a random username. Sometimes the irc server doesnt accept that username and then it just sits there. Should be fixed soon. Simpelest solution is restarting a few times.

**Comment by EldinZenderink** [comment]
Hi, version 0.4.0 has been released for most platforms: https://littleweeb.github.io/ or https://github.com/littleweeb/Desktop, should fix the issues you were having entirely ;)
