### ISSUE TITLE
Bad segregation of episodes

### ISSUE THREAD

**Issue by OgnistyPoland** [EldinZenderink/LittleWeeb#13]
![2018-03-11_221322](https://user-images.githubusercontent.com/32206254/37258513-91dca144-2579-11e8-8c92-a04362d9947e.png)

I think I don't need to write anything :P

**Comment by OgnistyPoland** [comment]
this anime has 13 episodes, but i see 25 (another bug)
![2018-03-13_193841](https://user-images.githubusercontent.com/32206254/37362720-45d0ef2a-26f6-11e8-9fb2-c532f908c938.png)

**Comment by EldinZenderink** [comment]
Probably because it finds magi episodes as well, another issue with the current logic that will be fixed ;).

**Comment by EldinZenderink** [comment]
Hi, version 0.4.0 has been released for most platforms: https://littleweeb.github.io/ or https://github.com/littleweeb/Desktop, should fix the issues you were having entirely ;)
