### ISSUE TITLE
Stuck on "waiting" for a lot of episodes

### ISSUE THREAD

**Issue by cheetahsweater** [EldinZenderink/LittleWeeb#14]
this is a really nice idea, and i'm stoked to see it perfected, but one problem i have is that when downloading episodes, it gets stuck on "waiting" and refuses to progress further.

**Comment by EldinZenderink** [comment]
Hi, thanks for the rapport, I am working on version 0.4.0 which will include a bunch of fixes and improvements regarding issues like this. Here a sneak preview (besides being able to close the loading screen manually, it will load faster :D, and more versions from different sub groups will be found):

Here a preview using One Piece: 
[Preview](https://i.imgur.com/WoHxW9Ht.gif)

For simplicity sake I will add a paging feature to it as well in the near future. Unfortunately I only have time to work on this in the weekends so it will take me a bit to get everything working. But the next update will be big :D.

**Comment by EldinZenderink** [comment]
Hi, version 0.4.0 has been released for most platforms: https://littleweeb.github.io/ or https://github.com/littleweeb/Desktop, should fix the issues you were having entirely ;)
