### ISSUE TITLE
Use kitsu API

### ISSUE THREAD

**Issue by Kcchouette** [EldinZenderink/LittleWeeb#15]
Hello
 Instead of MAL API (ex-Atarashii API) and anilist API, can you use kitsu API (https://kitsu.docs.apiary.io/)?

Thank you

**Comment by EldinZenderink** [comment]
Just a few more weeks until the new version will be available... :D development hasn't died yet.

**Comment by EldinZenderink** [comment]
Hi, version 0.4.0 has been released for most platforms: https://littleweeb.github.io/ or https://github.com/littleweeb/Desktop, with kitsu integrated! Well, not an account system of sync yet, but we use their api now!
