### ISSUE TITLE
unable to connect LittleWeeb client to LittleWeeb Server

### ISSUE THREAD

**Issue by KRDucky** [EldinZenderink/LittleWeeb#17]
As it stands, it is impossible to connect LittleWeeb Client to LittleWeeb Server. Adding the IP and port and saving does not save it.

**Comment by EldinZenderink** [comment]
Reference answer at: #18

**Comment by EldinZenderink** [comment]
Hi, version 0.4.0 has been released for most platforms: https://littleweeb.github.io/ or https://github.com/littleweeb/Desktop, should fix the issues you were having entirely ;)
