### ISSUE TITLE
Downloaded file(s) gets deleted when program is closed

### ISSUE THREAD

**Issue by Karmesinrot** [EldinZenderink/LittleWeeb#4]
I don't really know why but every time I close LittleWeeb the completed download files gets deleted somehow.

**Comment by EldinZenderink** [comment]
Interesting, I will take a look at when weekend arrives ^^. Could you provide some more information? Like operating system and what the console says before closing (next weekend I will add a log function that writes the output of the console to a file).

**Comment by Karmesinrot** [comment]
OS: Windows 10 Pro 64-bit build 16299

The console say before closing: WSDEBUG: Written message to server of size: 92
Cerebrate:** Closing Connection: Connection Lost

Only the last file downloaded gets deleted(ex. if I finished downloading from eps. 1-12, only ep.12 gets deleted the rest are fine and if I download only one file it gets deleted)

**Comment by EldinZenderink** [comment]
Gotta be honest, thought this one weird bug that happens only in a specific case, and I would be never able to actually see it happen... but it really happens... xD, thats not something that I should say right ^^, well atleast this makes it easier to solve, on it like a boss...

**Comment by EldinZenderink** [comment]
Please test it out for me :) I hope that it's fixed now in the little time that I had.

**Comment by Karmesinrot** [comment]
Working great now 👍 

To be honest I also didn't notice it even after downloading 5 different series until I started DLs on currently airing shows.
