### ISSUE TITLE
Unable to execute on Windows 10 virtual machine (Parallels Desktop)

### ISSUE THREAD

**Issue by jcraig999** [EldinZenderink/LittleWeeb#6]
Hi,
I am unable to run the executable file. When I click on it nothing happens. I have tried uninstalling and reinstalling on my VM with both 64 bit and 32-bit. Any help would be appreciated. Thanks.

**Comment by EldinZenderink** [comment]
Hmmm weird, which operating system?

Is .NET framework 4.5.2 installed?

Tried it with admin rights?

When you launch it, is there a littleweeb process running(check taskmanager)?

It's using chromium for its interface, did you check if normal chrome/chromium runs?

Is there a log file created in the exe directory of littleweeb? If so, can you post it?

**Comment by jcraig999** [comment]
I don't think there is a log file (or I am too ignorant to find it). Chrome runs fine. How do I find out what version of .NET I am running (when I tried to download 4.5.2 it said that it is either already installed for a later version is installed). My host is Mac OS 10 (I assume that's what you mean). I am running Windows 10 in a parallels desktop virtual machine.

**Comment by EldinZenderink** [comment]
The log files are called "awesomelogofc_XXXX" <- i was beeing cheeky with the filenames ;). That said, I will look into it, but it will take a bit. It's going to be hard to test as well, since I can't replicate the same situation as you are in. Maybe it's stupid of me to ask, but did  you try the solutions found here? http://kb.parallels.com/en/112983 

I am not familiar with parallels so I am not really sure what the issue could be. That said, I am working on making the backend separate from the front, running in just a basic console application, where you have to use a normal browser to launch the interface. If that works, its definitely something to do with winforms/cefsharp. But it will take me a bit to finish that update.

**Comment by jcraig999** [comment]
The log files are blank, and I tried the steps in the article you referenced with no luck. :-(

**Comment by EldinZenderink** [comment]
Would you be willing to test out the console version? It's not finished ,but it will at least tell us if the issue lies with cefsharp/winforms or not.

**Comment by jcraig999** [comment]
sure

**Comment by EldinZenderink** [comment]
alright, just a sec, i will upload it somewhere

**Comment by EldinZenderink** [comment]
https://drive.google.com/file/d/1FJG0vR6ENfkjhlosJ-t59QfIUQD0-H4p/view?usp=sharing 

Here ya go, its a lot smaller due to lacking the winforms part, you should be able to access the interface through the ip address that shows when you launch the console. (But then again, the api seems to be down, so possibly the interface will not show anything)

**Comment by jcraig999** [comment]
Blank Page. API is down

**Comment by EldinZenderink** [comment]
alright, but the console is shouting all kinds of messages right? If that's so, then it's definitely cefsharp (a browser for winforms based on chromium). I am not really sure why it's happening. Might be some issue with cefsharp. 

One other issue could be any kind of virusscanner, did you try to disable yours? Or did it mention something about my application?

**Comment by jcraig999** [comment]
Yes, I am getting all the messages on the console. I disabled all protection

**Comment by jcraig999** [comment]
And on the browser it comes up with a little red favicon when I type the URL for the server

**Comment by EldinZenderink** [comment]
Thats good, well, im sorry to say, but I think for the time being your stuck to use the console version, I will look into your issue, but first i need to fix the api problem :X, i hope that you can understand. 

I am a bit short on time so I am not sure if I will be able to fix it anytime soon :*(

**Comment by jcraig999** [comment]
Take your time. When you say you cannot fix the API problem anytime soon, what's the timeframe on that? A couple of months?

**Comment by EldinZenderink** [comment]
Oh no, actually, I already fixed the api part. Only issue is, like mentioned, I was in the middle of overhauling the whole interface to fit on smaller screens such as phones, but stuff aint as easy as I thought, (clipping etc). The console variant of littleweeb is supposed to run as a separate "server" on a NAS or pc that runs 24/7 where you can use your phone to download (and stream using a separate media player like mx player) anime. But before I can do that, I need to fix some issues were it doesn't really want to stay connected to the IRC for more than a day or so, and that's what is going to take a bit to fix as well. But I might release the api fix sooner (with the buggy phone interface, but working desktop interface). Actually I probably should do that, so I think that this weekend would be my goal.

**Comment by daniel-law** [comment]
@jcraig999 Hey, sorry to bump this issue like this. I was able to get LittleWeeb to run on my Macbook on Bootcamp, can you run the latest version on your VM in Parallels Desktop?

**Comment by EldinZenderink** [comment]
I'm sorry for my lack of response as well, but I just thought about the fact that the server version should run native on mac os through the terminal ;/ 

First you need to install this:

[http://www.mono-project.com/docs/getting-started/install/mac/](http://www.mono-project.com/docs/getting-started/install/mac/)

Then,

Just copy all the files in the zip into a directory of choice, open the terminal there (or navigate to it using the terminal) then type: `mono LittleWeebServer.exe`, technically it should run. 

Then using your browser, navigate to http://yourlocalip:6010 (or http://127.0.0.1:6010) (the terminal should say something like this as well) and you'd be able to use littleweeb for at least downloading anime.  (Tiny heads up, the server is currently not really working, to make it run with the current version (0.3.2) you need to make a copy of the GUI directory and rename the copy to GUIGUI (stupid mistake on my part)).

Hope that helps.

**Comment by EldinZenderink** [comment]
Hi, version 0.4.0 has been released for most platforms: https://littleweeb.github.io/ or https://github.com/littleweeb/Desktop, should fix the issues you were having entirely ;)

**Comment by jcraig999** [comment]
Thanks. It works great. Do you accept donations?

**Comment by EldinZenderink** [comment]
Glad it works, and no, I want to keep it non-profit. It feels wrong to accept money for something like this, acting in the grey area of the law. Technically what littleweeb does is not illegal, but to keep it as legal as possible, I won't be asking for any kind of donations nor would I use ads to generate income. 

I do not know what the future will bring, but as long as I am apart of the development of littleweeb I will make sure that everyone working on it has the same point of view as I regarding the marketability of littleweeb. To make sure that noone will profit from helping, aside from getting to use littleweeb ;) which is in my case profit enough.
