### ISSUE TITLE
Client title bar problem

### ISSUE THREAD

**Issue by Karmesinrot** [EldinZenderink/LittleWeeb#7]
After the latest release the client show to be not closing when prompt and shows (not responding) in the title bar.

Also I'm currently in Windows 10 somehow the Title bar of the App say LittleWeeb v 0.2.0 rather than LittleWeeb v 0.3.0.

**Comment by EldinZenderink** [comment]
Hi, thanks for reporting this, the version number issue is me being stupid and forgetting to change the title of the app ;). Thats a easy fix.

The other problem you mentioned, could you provide me with the log file (awesomelog.txt) and the irc log file (ircchatlog.txt) ?

I am experiencing the same issue so it's not really necessary but it will help.

Will work on it :D, might be able to fix it today. (Fuck my upcoming test ;) )

**Comment by Karmesinrot** [comment]
[awesomelogofc.txt](https://github.com/EldinZenderink/LittleWeeb/files/1526522/awesomelogofc.txt)

[ircchatlog.txt](https://github.com/EldinZenderink/LittleWeeb/files/1526524/ircchatlog.txt)

I also forgot to mention that the _open folder button_ is not anymore in the downloads tab only the Get Url, Abort and Delete buttons are found

**Comment by EldinZenderink** [comment]
Ah thanks for mentioning, I just noticed that issue as well (i really should be testing before releasing shit, my bad).  Weird thing is, on my end it's downloading... as I can see from your log it did start to download, did you check if the file has been created and/or did download (although maybe partially)? 

Maybe there is an issue with the interface.

**Comment by EldinZenderink** [comment]
So I did most of the bug fixes you mentioned, please try downloading again. If it still says waiting while downloading, try the server version and use your local browser. If you use chrome, press F12 and either screen cap/or copy the content of what you see here. (Best if you could copy it,  that would really help).

**Comment by Karmesinrot** [comment]
It's working downloading is fine now. I've check the default download location though and it shows this:
![download location](https://user-images.githubusercontent.com/32945140/33616102-dabdf632-da16-11e7-8c7f-d573d49624ad.png)

The Currently Airing sometimes doesn't load. I've also notice that the awesomelogofc.txt doesn't seem to log anything with the new release(so I can't upload it to GitHub).
[ircchatlog.txt](https://github.com/EldinZenderink/LittleWeeb/files/1531826/ircchatlog.txt)

**Comment by Karmesinrot** [comment]
log file is writing now.

For the currently airing it's both(at first launch and switching). And when switching I get stuck with it.
![cair](https://user-images.githubusercontent.com/32945140/33619340-ea82ee5c-da1f-11e7-8c10-c7f814c640e1.png)

**Comment by EldinZenderink** [comment]
alright, if the log file is writing, please provide it here ;D it will probably show me the issue. If you have time, could you test the server as well and copy the log by pressing F12 and tell me what the console is showing? That should really help with finding a solution.

**Comment by Karmesinrot** [comment]
[awesomelogofc.txt](https://github.com/EldinZenderink/LittleWeeb/files/1532121/awesomelogofc.txt)
[ircchatlog.txt](https://github.com/EldinZenderink/LittleWeeb/files/1532123/ircchatlog.txt)
