### ISSUE TITLE
Some bugs

### ISSUE THREAD

**Issue by ShittyGuy** [EldinZenderink/LittleWeeb#9]
First of all, I wanna thank you for this nizze programme. It's a nice way to find some quality anime without relying on torrents. But here are some bugs I found:

OVAs disappear after returning to the tab:
https://gfycat.com/FormalBlackandwhiteGnu

It's impossible to uncheck the first episode after checking it because the download button is above it:
https://gfycat.com/DismalNearLeopardseal

Infinite loading (no option to cancel it):
https://i.imgur.com/Fj8reoi.png

Green and red colors are on the wrong button:
https://i.imgur.com/v1TJ0Wf.png

And it would be nice if there is an option to automatically create a subdirectory for every anime

**Comment by EldinZenderink** [comment]
Hmmm weird, I am sorry to say this, but unfortunately due to time restraints IRL I am not able to work on my hobby projects ;(, I hope to get some time of in about a week or so, so I might be able to take a look then, sorry for the inconvenience :(

Anyway thanks for reporting!

**Comment by EldinZenderink** [comment]
Hi, version 0.4.0 has been released for most platforms: https://littleweeb.github.io/ or https://github.com/littleweeb/Desktop, should fix the issues you were having entirely ;)
